spring:
  # 多数据源配置
  datasource:
    druid:
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: ENC(VQ3MhEocEDT12d9FqEX5cQ==)
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.128.62.33:3306/jy_example?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: ENC(VQ3MhEocEDT12d9FqEX5cQ==)
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
        initialSize: 5
        minIdle: 5
        maxActive: 20
  # redisConfig
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 10.128.62.32 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 1000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
  # kafka配置
  kafka:
    bootstrap-servers: 10.128.62.35:9092
    producer: # service
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger:
          ms: 1
    consumer: # consumer
      group-id: kafkaGroup
      enable-auto-commit: true # 是否自动提交
      auto-commit-interval: 100 # 自动提交时间间隔
      auto:
        offset:
          reset: latest # 实时生产，实时消费，不会从头开始消费
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session:
          timeout:
            ms: 15000
  # elasticsearch配置
  data:
    elasticsearch:
      cluster-name: prod_es_test # elasticsearch集群名称
      cluster-nodes: 10.128.62.33:9300 # 节点的地址
      repositories:
        enabled: true # 是否开启本地存储
      rest:
        uris: http://10.128.62.33:9200 # http协议，用于外部通讯，防止actuator对elasticsearch健康检查失败

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.jy.entity

# 加密盐 也可以项目部署时传入java -jar -Djasypt.encryptor.password=G0CvDz7oJn6 xxx.jar
jasypt:
  encryptor:
    password: JY@myt11

#swagger true时才启用swagger
swagger:
  enable: true